### ISSUE TITLE
ValueError: operands could not be broadcast together

### ISSUE THREAD

**Issue by flobra** [sfortma2/scranPY#1]
Hi Seth,

first of all thanks a lot for publishing this package!

A few weeks ago I wanted to try scranPY out on one of the scanpy datasets, specifically the [3kpbmc](https://scanpy.readthedocs.io/en/stable/generated/scanpy.datasets.pbmc3k.html) one. 

Following mostly all the steps from the notebook, I got the error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 2
      1 import scranPY
----> 2 scranPY.compute_sum_factors(adata, clusters='norm_groups', parallelize=True, algorithm='CVXPY', max_size=3000, plotting=True,
      3     lower_bound=0.4, normalize_counts=False)

File ~/mambaforge/envs/scranPY_test/lib/python3.11/site-packages/scranPY/main.py:250, in compute_sum_factors(adata, sizes, clusters, min_mean, max_size, parallelize, algorithm, stopwatch, plotting, lower_bound, normalize_counts, log1p, layer, save_plots_dir)
    248 lib_sizes = np.sum(adata.X, axis=1) ##3
    249 lib_sizes = lib_sizes / np.mean(lib_sizes) 
--> 250 exprs = (adata.X.T / lib_sizes).T ##4
    251 min_mean = guess_min_mean(adata.X, min_mean=min_mean) ##5
    252 print('min_mean = ', min_mean)

File ~/mambaforge/envs/scranPY_test/lib/python3.11/site-packages/scipy/sparse/_base.py:686, in spmatrix.__truediv__(self, other)
    685 def __truediv__(self, other):
--> 686     return self._divide(other, true_divide=True)

File ~/mambaforge/envs/scranPY_test/lib/python3.11/site-packages/scipy/sparse/_base.py:665, in spmatrix._divide(self, other, true_divide, rdivide)
    663 if not rdivide:
    664     if true_divide:
--> 665         return np.true_divide(self.todense(), other)
    666     else:
    667         return np.divide(self.todense(), other)

ValueError: operands could not be broadcast together with shapes (32738,2700) (2700,1) 
```

I also tried it with two other datasets I had on my computer and it had the same broadcast problem.

However, when trying it with the [Paul15](https://scanpy.readthedocs.io/en/stable/generated/scanpy.datasets.paul15.html#scanpy.datasets.paul15) dataset (also from scanpy), normalization actually completed. 

I uploaded my notebook trying out Scranpy including package version numbers [here](https://github.com/flobra/scranPY_test/blob/main/scranPY_test.ipynb). Do you think you maybe could also provide the environment and dataset you used to test ScranPY?

All the best,

Flo

**Comment by flobra** [comment]
Okay, I guess reading this tweet

https://twitter.com/sfortma2/status/1673448503543230464?s=20

would've made my life easier😅 Works perfect when prior converting all sparse matrices into dense ones using 

`adata.X = adata.X.A`

or something similar!

**Comment by sfortma2** [comment]
Hi Flo. I'm sorry I missed your messages! You're correct, currently scranPY only supports dense arrays as input. I'll update the github page to reflect this until the functionality is implemented. Thanks!
