### ISSUE TITLE
Clusters=None raise an error  as  cluster is assigned  in the sourcecode before the  if statement ""clusters = adata.obs[clusters].astype('category') , if clusters is not None""

### ISSUE THREAD

**Issue by Marwansha** [sfortma2/scranPY#2]
scranPY.compute_sum_factors(adata, clusters=None, algorithm='CVXPY', max_size=3000, plotting=True, lower_bound=0.4, save_plots_dir='.')
---------------------------------------------------------------------------

> KeyError                                  Traceback (most recent call last)
> File ~/venvs/doublets/lib/python3.8/site-packages/pandas/core/indexes/base.py:3653, in Index.get_loc(self, key)
>    3652 try:
> -> 3653     return self._engine.get_loc(casted_key)
>    3654 except KeyError as err:
> 
> File ~/venvs/doublets/lib/python3.8/site-packages/pandas/_libs/index.pyx:147, in pandas._libs.index.IndexEngine.get_loc()
> 
> File ~/venvs/doublets/lib/python3.8/site-packages/pandas/_libs/index.pyx:176, in pandas._libs.index.IndexEngine.get_loc()
> 
> File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: None
> 
> The above exception was the direct cause of the following exception:
> 
> KeyError                                  Traceback (most recent call last)
> Cell In[30], line 1
> ----> 1 scranPY.compute_sum_factors(adata, clusters=None, algorithm='CVXPY', max_size=3000, plotting=True, lower_bound=0.4, save_plots_dir='.')
> 
> File ~/venvs/doublets/lib/python3.8/site-packages/scranPY/main.py:221, in compute_sum_factors(adata, sizes, clusters, min_mean, max_size, parallelize, algorithm, stopwatch, plotting, lower_bound, normalize_counts, log1p, layer, save_plots_dir)
>     218 def compute_sum_factors(adata=AnnData, sizes=np.arange(21, 102, 5), clusters=None, min_mean=None, max_size=3000, parallelize=True, algorithm='CVXPY', stopwatch=True, plotting=True, lower_bound=0.1, normalize_counts=False, log1p=False, layer='scranPY', save_plots_dir=None):
>     220     start_time = time.time()
> --> 221     clusters = adata.obs[clusters].astype('category')
>     223     if clusters is not None:
>     224         print('Current smallest cluster = ', clusters.value_counts().min(),' cells.')
> 
> File ~/venvs/doublets/lib/python3.8/site-packages/pandas/core/frame.py:3761, in DataFrame.__getitem__(self, key)
>    3759 if self.columns.nlevels > 1:
>    3760     return self._getitem_multilevel(key)
> -> 3761 indexer = self.columns.get_loc(key)
>    3762 if is_integer(indexer):
>    3763     indexer = [indexer]
> 
> File ~/venvs/doublets/lib/python3.8/site-packages/pandas/core/indexes/base.py:3655, in Index.get_loc(self, key)
>    3653     return self._engine.get_loc(casted_key)
>    3654 except KeyError as err:
> -> 3655     raise KeyError(key) from err
>    3656 except TypeError:
>    3657     # If we have a listlike key, _check_indexing_error will raise
>    3658     #  InvalidIndexError. Otherwise we fall through and re-raise
>    3659     #  the TypeError.
>    3660     self._check_indexing_error(key)
> 
> KeyError: None

and this is the source , it look like  the source code  for scranPY.compute_sum_factors tries to access the clusters column in adata.obs and cast it to a category type:   clusters = adata.obs[clusters].astype('category')  and there is no option for being as none  here is copy of the errored part i think 
 **### clusters = adata.obs[clusters].astype('category') , if clusters is not None:**
**here is source code** 
```
Signature:
scranPY.compute_sum_factors(
    adata=<class 'anndata._core.anndata.AnnData'>,
    sizes=array([ 21,  26,  31,  36,  41,  46,  51,  56,  61,  66,  71,  76,  81,
        86,  91,  96, 101]),
    clusters=None,
    min_mean=None,
    max_size=3000,
    parallelize=True,
    algorithm='CVXPY',
    stopwatch=True,
    plotting=True,
    lower_bound=0.1,
    normalize_counts=False,
    log1p=False,
    layer='scranPY',
    save_plots_dir=None,
)
Docstring: <no docstring>
Source:   
def compute_sum_factors(adata=AnnData, sizes=np.arange(21, 102, 5), clusters=None, min_mean=None, max_size=3000, parallelize=True, algorithm='CVXPY', stopwatch=True, plotting=True, lower_bound=0.1, normalize_counts=False, log1p=False, layer='scranPY', save_plots_dir=None):
    
    start_time = time.time()
   clusters = adata.obs[clusters].astype('category')

    if clusters is not None:
        print('Current smallest cluster = ', clusters.value_counts().min(),' cells.')
        if clusters.value_counts().min() < sizes.max(): 
            if 41 > clusters.value_counts().min(): ## we want at least 5 pool sizes to compare with
                if 30 > clusters.value_counts().min():
                    raise ValueError("You're passing a cluster that is too small. Minimum size is 30 cells.")
                else:
                    print("Warning: you're passing a very small cluster that contains 40 or less cells. Pool sizes have been readjusted.")
                    sizes=np.arange(11, clusters.value_counts().min(), 5)
                    sizes = np.array(sizes, dtype=int)
            else:
                print("Warning: you're passing a small cluster that contains less than 100 cells. Pool sizes have been readjusted.")
                sizes=np.arange(21, clusters.value_counts().min(), 5)
                sizes = np.array(sizes, dtype=int)
        else:
            sizes = np.array(sizes, dtype=int)
```

**Comment by sfortma2** [comment]
Hi @Marwansha, 

Thanks for raising this issue. I have corrected the error in the current release (v1.1), so clusters=None will work now as originally intended. Thanks!

**Comment by Marwansha** [comment]
Thanks for the help,  now using  clusters=none will it perform a default clustering  or the scranpy can manage without doing any clustering?

as when i did a preliminary clustering using scanpy i got errors that tha minimum size of cluster accepted is 30 cells, which is a problem for me as i am doing clustering on different libraries/ batches and i don't want to introduce biases by using d iffrent resolution of clustering  for some libraries to avoid this small cluster issues

**Comment by sfortma2** [comment]
When clusters=None, scranPY assigns all cells to the same "cluster". If the total number of cells exceeds max_size then that "cluster" is divided into the minimum number of smaller "clusters" needed to ensure that all fall below the max_size parameter. The assignment of cells to new "clusters" is done in a non-random, sequential manner based on their position in the original array. This is identical to how r-scran handles the same scenario when clusters=NULL.

Regarding your statement about minimum cluster size, scranPY as well as r-scran rely on pooling samples into different size pools (usually 5 different pool sizes). When there are less than 30 cells in a cluster, there are insufficient data for grouping cells into these 5 pools. This results in unreliable calculations for that cluster. If you have clusters that have less than 30 cells, you should consider reclustering at a lower resolution or you should assign those <30 cells to another preexisting cluster just for the normalization step.

**Comment by Marwansha** [comment]
Thanks alot 
Have a nice day
